### ISSUE TITLE
Elements without content shouldn't affect LS

### ISSUE THREAD

**Issue by patrickhulce** [WICG/layout-instability#45] opened 2020-06-05 15:25 UTC
Hi there from the Lighthouse team 👋  :)

I'm bringing up an issue that was been raised a few times over in Lighthouse where we expose the CLS of the page (https://github.com/GoogleChrome/lighthouse/issues/10873 is a particularly useful discussion that highlights several rough edges of CLS if you're interested).

The gist is that when dynamically loading in content into an app shell, you have to do some CSS gymnastics to position your loading spinner to ensure that the empty positioning divs don't artificially inflate CLS.

A particularly rough example is https://melodic-class.glitch.me/cls-empty.html which clearly has no user perceived layout shift yet gets a CLS of 0.426

I'm wondering if it could be considered that elements without any content (text or images) are excluded from layout shift.

**Comment by skobes** [comment] 2020-06-26 14:55
Thanks for raising this.  It is a known limitation of CLS that we do not currently distinguish elements that don't paint any content (but have non-zero fixed size).

I have filed crbug.com/1099350 to track exploring better ways of handling this in Chromium.

**Comment by wangxianzhu** [comment] 2021-02-04 19:43
Should this be merged into #61?

**Comment by skobes** [comment] 2021-02-05 22:26
Duplicate of #61

**Closed by skobes** 2021-02-05 22:26 UTC
